---

- hosts: ubuntu.my
  become: true
  tasks:
  - name: Install zabbix-agent on Ubuntu
    apt:
        name=zabbix-agent
        state=present

  - name: Install zabbix release package
    apt:
      deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu20.04_all.deb

    when:
       ansible_os_family == "Debian"
    notify:
        zabbix-agent systemd

- hosts: centos.my
  become: true
  tasks:
  - name: Install zabbix-release CentOS 7
    yum:
      name: https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-release-6.0-4.el7.noarch.rpm
  - name: install zabbix-agent
    yum: name=zabbix-agent state=present

    when:
        ansible_os_family == "RedHat"
  - name: Start zabbix-agent
    service:
      name: zabbix-agent
      state: started
      enabled: yes
